<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Inspection>
 */
class InspectionFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $states = ["Alaska", "Alabama", "Arkansas", "American Samoa", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia", "Delaware", "Florida", "Georgia", "Guam", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Virginia", "Virgin Islands", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"];
        return [
            'form_steps' => [1, 2, 3, 4, 5, 6, 7, 8, 9],
            'name' => $this->faker->name,
            'address' => $this->faker->address,
            'address_2' => $this->faker->text,
            'city' => $this->faker->city,
            'state' => array_rand($states),
            'zip' => $this->faker->postcode,
            'country' => $this->faker->country,
            'overall_rating' => $this->faker->numberBetween(1, 100),
            'rating_scale' => 'MBA',
            'inspection_date' => $this->faker->dateTimeThisYear->format('Y-m-d H:i:s'),
            'primary_type' => $this->faker->word,
            'secondary_type' => $this->faker->word,
            'servicer_loan_info' => [
                'servicer_name' => $this->faker->name,
                'loan_number' => $this->faker->randomNumber(),
                'property_id' => $this->faker->word,
                'servicer_inspection_id' => $this->faker->word,
                'original_loan_amount' => $this->faker->randomNumber(),
                'loan_balance' => $this->faker->randomNumber(),
                'loan_balance_date' => $this->faker->dateTimeThisDecade->format('Y-m-d'),
                'loan_owner' => $this->faker->sentence,
                'investor_number' => $this->faker->randomNumber(),
                'investor_loan_number' => $this->faker->randomNumber(),
                'asset_manager_name' => $this->faker->name,
                'asset_manager_phone' => $this->faker->phoneNumber,
                'asset_manager_email' => $this->faker->email,
                'report_reviewed_by' => $this->faker->name,
            ],
            'contact_inspector_info' => [
                'contact_company' => $this->faker->company,
                'contact_name' => $this->faker->name,
                'contact_phone' => $this->faker->phoneNumber,
                'contact_email' => $this->faker->email,
                'inspection_company' => $this->faker->company,
                'inspector_name' => $this->faker->name,
                'inspector_company_phone' => $this->faker->phoneNumber,
                'inspector_id' => $this->faker->word,
            ],
            'management_onsite_info' => [
                'company_name' => $this->faker->company,
                'onsite_contact' => $this->faker->name,
                'role_title' => $this->faker->word,
                'mgmt_affiliation' => $this->faker->sentence,
                'phone_number' => $this->faker->phoneNumber,
                'mgmt_interview' => $this->faker->word,
                'time_at_property' => $this->faker->word,
                'management_changed' => $this->faker->word,
            ],
            'comments' => [
                'servicer_comments' => $this->faker->sentence,
                'inspector_comments' => $this->faker->sentence,
            ],
            'profile_occupancy_info' => [
                'number_of_buildings' => $this->faker->randomNumber(),
                'number_of_floors' => $this->faker->randomNumber(),
                'number_of_elevators' => $this->faker->randomNumber(),
                'number_of_parking_spaces' => $this->faker->randomNumber(),
                'year_built' => $this->faker->year,
                'year_renovated' => $this->faker->year,
                'annual_occupancy' => $this->faker->randomNumber(),
                'annual_turnover' => $this->faker->randomNumber(),
                'rent_roll_obtained' => $this->faker->randomNumber(),
                'rent_roll_date' => $this->faker->date(),
                'is_affordable_housing' => $this->faker->boolean,
                'unit_of_measurement_used' => $this->faker->word,
                'num_of_rooms' => $this->faker->randomNumber(),
                'occupied_space' => $this->faker->randomNumber(),
                'vacant_space' => $this->faker->randomNumber(),
                'occupied_units_inspected' => $this->faker->randomNumber(),
                'vacant_units_inspected' => $this->faker->randomNumber(),
                'total_sq_feet_gross' => $this->faker->randomNumber(),
                'total_sq_feet_net' => $this->faker->randomNumber(),
                'dark_space' => $this->faker->word,
                'down_space' => $this->faker->word,
                'num_of_down_units' => $this->faker->randomNumber(),
                'dark_down_space_description' => $this->faker->sentence,
                'rental_concessions_offered' => $this->faker->word,
                'describe_rental_concession' => $this->faker->sentence,
                'franchise_name' => $this->faker->name,
                'franchise_change_since_last_inspection' => $this->faker->word,
            ],
            'capital_expenditures' => [
                'Expenditure' => [
                    [
                        'repair_description' => $this->faker->sentence,
                        'identified_cost' => $this->faker->randomNumber(),
                        'status' => $this->faker->word,
                    ],
                ],
            ],
            'operation_maintenance_plans' => [
                'Plan' => [
                    [
                        'plan_name' => $this->faker->word,
                        'management_aware' => $this->faker->word,
                        'plan_available' => $this->faker->word,
                    ],
                ],
                'describe_om_plans' => $this->faker->sentence,
            ],
            'neighborhood_site_data' => [
                'name_or_type_competitor_1' => $this->faker->name,
                'distance_competitor_1' => $this->faker->randomNumber(),
                'name_or_type_competitor_2' => $this->faker->name,
                'distance_competitor_2' => $this->faker->randomNumber(),
                'single_family_percent_use' => $this->faker->randomNumber(),
                'multi_family_percent_use' => $this->faker->randomNumber(),
                'commercial_percent_use' => $this->faker->randomNumber(),
                'industrial_percent_use' => $this->faker->randomNumber(),
                'is_declining_area' => $this->faker->word,
                'is_new_construction_in_area' => $this->faker->word,
                'area_trends_description' => $this->faker->sentence,
                'collateral_description' => $this->faker->sentence,
            ],
            'physical_condition' => [
                'curb_appeal_rating' => $this->faker->word,
                'curb_appeal_trend' => $this->faker->word,
                'curb_appeal_inspector_comments' => $this->faker->sentence,
                'site_rating' => $this->faker->word,
                'site_trend' => $this->faker->word,
                'site_inspector_comments' => $this->faker->sentence,
                'mechanical_rating' => $this->faker->word,
                'mechanical_trend' => $this->faker->word,
                'mechanical_inspector_comments' => $this->faker->sentence,
                'exterior_rating' => $this->faker->word,
                'exterior_trend' => $this->faker->word,
                'exterior_inspector_comments' => $this->faker->sentence,
                'roofs_rating' => $this->faker->word,
                'roofs_trend' => $this->faker->word,
                'roofs_inspector_comments' => $this->faker->sentence,
                'occupied_rating' => $this->faker->word,
                'occupied_trend' => $this->faker->word,
                'occupied_inspector_comments' => $this->faker->sentence,
                'vacant_rating' => $this->faker->word,
                'vacant_trend' => $this->faker->word,
                'vacant_inspector_comments' => $this->faker->sentence,
                'down_rating' => $this->faker->word,
                'down_trend' => $this->faker->word,
                'down_inspector_comments' => $this->faker->sentence,
                'interior_common_rating' => $this->faker->word,
                'interior_common_trend' => $this->faker->word,
                'interior_common_inspector_comments' => $this->faker->sentence,
                'amenities_rating' => $this->faker->word,
                'amenities_trend' => $this->faker->word,
                'amenities_inspector_comments' => $this->faker->sentence,
                'interior_rating' => $this->faker->word,
                'interior_trend' => $this->faker->word,
                'interior_inspector_comments' => $this->faker->sentence,
                'exterior_additional_desc' => $this->faker->sentence,
                'interior_additional_desc' => $this->faker->sentence,
                'deferred_items' => [
                    [
                        'description' => $this->faker->sentence,
                        'rating' => $this->faker->word,
                        'life_safety' => $this->faker->sentence,
                        'estimated_cost' => $this->faker->randomNumber(),
                    ],
                ],
            ],
            'images' => [
                [
                    'photo_type' => $this->faker->word,
                    'photo_description' => $this->faker->sentence,
                    'photo_url' => [],
                ],
            ],
            'rent_roll' => [
                'rent_roll_attached' => $this->faker->word,
                'rent_roll_missing_reason' => null,
                'rent_roll_summary_attached' => $this->faker->word,
                'single_tenant_property' => $this->faker->word,
                'hospitality_property' => $this->faker->word,
                'ytd_adr' => null,
                'revpar' => null,
                'ado' => null,
                'tenant_info' => [
                    [
                        'tenant_name' => $this->faker->name,
                        'expiration' => $this->faker->sentence,
                        'sq_ft' => $this->faker->randomNumber(),
                        'nra_percentage' => $this->faker->sentence,
                        'annual_rent' => $this->faker->randomNumber(),
                        'rent_per_sqft' => $this->faker->randomNumber(),
                    ],
                ],
            ],
            'mgmt_interview' => [
                'management_company_name' => $this->faker->company,
                'name_information_source' => $this->faker->name,
                'role_title_information_source' => $this->faker->word,
                'management_affiliation' => $this->faker->sentence,
                'phone_number' => $this->faker->phoneNumber,
                'email_address' => $this->faker->email,
                'length_at_property' => $this->faker->word,
                'mgmt_change_last_inspection' => $this->faker->word,
                'property_performance_question' => $this->faker->word,
                'average_vacancy_percentage' => $this->faker->sentence,
                'average_rent_current' => $this->faker->sentence,
                'vacancy_comparison_last_year' => $this->faker->word,
                'vacany_variance_explanation' => $this->faker->sentence,
                'Amount of the last rental increase' => $this->faker->sentence,
                'Date of last rental increase' => $this->faker->date(),
                'Number of Administration Employees' => $this->faker->randomNumber(),
                'Number of Maintenance Employees' => $this->faker->randomNumber(),
                'Heat at the Property' => $this->faker->word,
                'Water at the Property' => $this->faker->word,
                'Electric at the Property' => $this->faker->word,
                'Gas at the Property' => $this->faker->word,
                'Trash at the Property' => $this->faker->word,
                'Cable at the Property' => $this->faker->word,
                'tenant_profile' => [
                    'Corporate' => $this->faker->word,
                    'Military' => $this->faker->word,
                    'Seasonal' => $this->faker->word,
                    'Seniors' => $this->faker->word,
                    'Students' => $this->faker->word,
                    'Other' => $this->faker->word,
                ],
                'property_events' => [
                    'key_employee_replaced' => $this->faker->word,
                    'significant_propoerty_damage' => $this->faker->word,
                    'significant_propoerty_damage_explanation' => $this->faker->sentence,
                    'code_violation_received' => $this->faker->word,
                    'code_violation_explanation' => $this->faker->sentence,
                    'significant_rehab_construction' => $this->faker->word,
                    'significant_rehab_construction_explanation' => $this->faker->sentence,
                    'franchise_agreement_change' => $this->faker->word,
                    'franchise_agreement_change_explanation' => $this->faker->sentence,
                    'lawsuits_pending' => $this->faker->word,
                    'lawsuits_pending_explanation' => $this->faker->sentence,
                    'special_assessments' => $this->faker->word,
                    'special_assessments_explanation' => $this->faker->sentence,
                    'short_term_leases' => $this->faker->word,
                    'short_term_leases_explanation' => $this->faker->sentence,
                    'management_evaluation_comments' => $this->faker->sentence,
                ],
            ],
            'multifamily' => [
                'any_commercial_units' => $this->faker->word,
                'num_commercial_units' => $this->faker->randomNumber(),
                'commercial_units_inspected' => $this->faker->randomNumber(),
                'multifamily_unit_breakdown' => [
                    'unit_info' => [
                        [
                            'bedrooms' => $this->faker->randomNumber(),
                            'baths' => $this->faker->randomNumber(),
                            'num_of_units' => $this->faker->randomNumber(),
                            'avg_sqft_unit' => $this->faker->randomNumber(),
                            'avg_rent' => $this->faker->randomNumber(),
                            'occupied' => $this->faker->randomNumber(),
                            'non-revenue' => $this->faker->randomNumber(),
                            'vacant' => $this->faker->randomNumber(),
                            'down' => $this->faker->randomNumber(),
                            'inspected' => $this->faker->randomNumber(),
                        ],
                    ],
                ],
                'unit_detail_report' => [
                    'unit_detail' => [
                        [
                            'unit_no' => $this->faker->word,
                            'bedrooms' => $this->faker->randomNumber(),
                            'baths' => $this->faker->randomNumber(),
                            'square_feet' => $this->faker->randomNumber(),
                            'asking_rent' => $this->faker->randomNumber(),
                            'current_use' => $this->faker->sentence,
                            'overall_condition' => $this->faker->sentence,
                        ],
                    ],
                ],
                'general_comments' => $this->faker->sentence,
            ],
            'fannie_mae_assmt' => [
                'limitations_of_field_assessment' => [
                    'limitations_experienced' => [
                        'Management experience on the property is less than six months?',
                        'Significant portions of the common areas, amenities or basements, etc. were unavailable for assessment?',
                        'Snow was covering most exterior areas (parking lots, roofs, landscape areas)?',
                    ],
                    'limitation_comment' => $this->faker->sentence,
                ],
                'property_assessment_ratings' => [
                    'life_safety' => $this->faker->sentence,
                    'life_safety_comments' => $this->faker->sentence,
                    'deffered_maintenance' => $this->faker->sentence,
                    'deffered_maintenance_comments' => $this->faker->sentence,
                    'routine_maintenance' => $this->faker->sentence,
                    'routine_maintenance_comments' => $this->faker->sentence,
                    'capital_needs' => $this->faker->sentence,
                    'capital_needs_comments' => $this->faker->sentence,
                    'volume_of_issues_noted' => $this->faker->sentence,
                    'volume_of_issues_noted_comments' => $this->faker->sentence,
                    'overall_property_rating' => $this->faker->randomNumber(),
                    'overall_property_rating_comments' => $this->faker->sentence,
                    'seller_servicer_certification' => [
                        'date' => $this->faker->date(),
                        'first_name' => $this->faker->firstName,
                        'last_name' => $this->faker->lastName,
                        'title' => $this->faker->word,
                        'phone_number' => $this->faker->phoneNumber,
                        'email_address' => $this->faker->email,
                    ],
                ],
            ],
            'fre_assmt' => null,
            'repairs_verification' => [
                'property_info' => [
                    'name' => $this->faker->word,
                    'address' => $this->faker->address,
                    'address_2' => $this->faker->sentence,
                    'city' => $this->faker->city,
                    'state' => $this->faker->randomNumber(),
                    'zip' => $this->faker->postcode,
                    'country' => $this->faker->country,
                ],
                'contact_company' => $this->faker->company,
                'contact_name' => $this->faker->name,
                'contact_phone' => $this->faker->phoneNumber,
                'contact_email' => $this->faker->email,
                'inspection_company' => $this->faker->company,
                'inspector_name' => $this->faker->name,
                'inspector_company_phone' => $this->faker->phoneNumber,
                'inspector_id' => $this->faker->word,
                'servicer_name' => $this->faker->name,
                'loan_number' => $this->faker->randomNumber(),
                'primary_type' => $this->faker->word,
                'expected_percentage_complete' => $this->faker->randomNumber(),
                'overall_observed_percentage_complete' => $this->faker->randomNumber(),
                'general_summary_comments' => $this->faker->sentence,
                'verification_list' => [
                    [
                        'item_description' => $this->faker->sentence,
                        'inspector_comments' => $this->faker->sentence,
                        'photo' => [],
                        'repair_status' => $this->faker->word,
                    ],
                ],
            ],
            'hospitals' => [
                'new_patients_accepted' => $this->faker->word,
                'admission_waiting_period' => $this->faker->word,
                'proximity_to_hospital' => $this->faker->word,
                'level_of_care_breakdown' => [
                    'unit_info' => [
                        [
                            'unit_type' => $this->faker->word,
                            'total_beds' => $this->faker->randomNumber(),
                            'occupied_beds' => $this->faker->randomNumber(),
                            'total_units' => $this->faker->randomNumber(),
                            'occupied_units' => $this->faker->randomNumber(),
                            'average_sq_feet_unit' => $this->faker->randomNumber(),
                            'monthly_rent' => $this->faker->randomNumber(),
                        ],
                    ],
                ],
                'administrator_name' => $this->faker->name,
                'administrator_length_at_property' => $this->faker->word,
                'director_nursing_name' => $this->faker->name,
                'director_nursing_length_at_property' => $this->faker->word,
                'number_of_staff' => $this->faker->randomNumber(),
                'number_of_nursing_staff' => $this->faker->randomNumber(),
                'property_events' => [
                    'key_employee_replaced' => $this->faker->word,
                    'significant_propoerty_damage' => $this->faker->word,
                    'significant_propoerty_damage_explanation' => $this->faker->sentence,
                    'code_violation_received' => $this->faker->word,
                    'code_violation_explanation' => $this->faker->sentence,
                    'significant_rehab_construction' => $this->faker->word,
                    'significant_rehab_construction_explanation' => $this->faker->sentence,
                    'franchise_agreement_change' => $this->faker->word,
                    'franchise_agreement_change_explanation' => $this->faker->sentence,
                    'lawsuits_pending' => $this->faker->word,
                    'lawsuits_pending_explanation' => $this->faker->sentence,
                    'special_assessments' => $this->faker->word,
                    'special_assessments_explanation' => $this->faker->sentence,
                ],
                'general_comments' => $this->faker->sentence,
                'fannie_mae_assmt' => [
                    'limitations_of_field_assessment' => [
                        'limitations_experienced' => [
                            'Management experience on the property is less than six months?',
                            'Significant portions of the common areas, amenities or basements, etc. were unavailable for assessment?',
                            'Snow was covering most exterior areas (parking lots, roofs, landscape areas)?',
                        ],
                        'limitation_comment' => $this->faker->sentence,
                    ],
                    'property_assessment_ratings' => [
                        'life_safety' => $this->faker->sentence,
                        'life_safety_comments' => $this->faker->sentence,
                        'deffered_maintenance' => $this->faker->sentence,
                        'deffered_maintenance_comments' => $this->faker->sentence,
                        'routine_maintenance' => $this->faker->sentence,
                        'routine_maintenance_comments' => $this->faker->sentence,
                        'capital_needs' => $this->faker->sentence,
                        'capital_needs_comments' => $this->faker->sentence,
                        'volume_of_issues_noted' => $this->faker->sentence,
                        'volume_of_issues_noted_comments' => $this->faker->sentence,
                        'overall_property_rating' => $this->faker->randomNumber(),
                        'overall_property_rating_comments' => $this->faker->sentence,
                        'seller_servicer_certification' => [
                            'date' => $this->faker->date(),
                            'first_name' => $this->faker->firstName,
                            'last_name' => $this->faker->lastName,
                            'title' => $this->faker->word,
                            'phone_number' => $this->faker->phoneNumber,
                            'email_address' => $this->faker->email,
                        ],
                    ],
                ],
                'fre_assmt' => null,
                'repairs_verification' => [
                    'verification_list' => [
                        [
                            'item_description' => $this->faker->sentence,
                            'inspector_comments' => $this->faker->sentence,
                            'photo' => [],
                            'repair_status' => $this->faker->word,
                        ],
                    ],
                ],
                'property_info' => [
                    'name' => $this->faker->word,
                    'address' => $this->faker->address,
                    'address_2' => $this->faker->sentence,
                    'city' => $this->faker->city,
                    'state' => $this->faker->randomNumber(),
                    'zip' => $this->faker->postcode,
                    'country' => $this->faker->country,
                ],
                'contact_company' => $this->faker->company,
                'contact_name' => $this->faker->name,
                'contact_phone' => $this->faker->phoneNumber,
                'contact_email' => $this->faker->email,
                'inspection_company' => $this->faker->company,
                'inspector_name' => $this->faker->name,
                'inspector_company_phone' => $this->faker->phoneNumber,
                'inspector_id' => $this->faker->word,
                'servicer_name' => $this->faker->name,
                'loan_number' => $this->faker->randomNumber(),
                'primary_type' => $this->faker->word,
                'expected_percentage_complete' => $this->faker->randomNumber(),
                'overall_observed_percentage_complete' => $this->faker->randomNumber(),
                'general_summary_comments' => $this->faker->sentence,
            ],
            'senior_supplement' => null,
        ];
    }
}
